// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_project_api.app.DbContextInit;

#nullable disable

namespace web_project_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220419230412_ajusteFK")]
    partial class ajusteFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("web_project_api.app.Model.Allocation", b =>
                {
                    b.Property<int>("allocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("accountNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("allocationName")
                        .HasColumnType("longtext");

                    b.Property<int>("tradeId")
                        .HasColumnType("int");

                    b.Property<int>("unit")
                        .HasColumnType("int");

                    b.HasKey("allocationId");

                    b.HasIndex("tradeId");

                    b.ToTable("Allocation");
                });

            modelBuilder.Entity("web_project_api.app.Model.Trade", b =>
                {
                    b.Property<int>("tradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tradeStatusCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("tradingDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("tradeId");

                    b.ToTable("Trade");
                });

            modelBuilder.Entity("web_project_api.app.Model.Allocation", b =>
                {
                    b.HasOne("web_project_api.app.Model.Trade", "trade")
                        .WithMany("_allocations")
                        .HasForeignKey("tradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trade");
                });

            modelBuilder.Entity("web_project_api.app.Model.Trade", b =>
                {
                    b.Navigation("_allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
